import React from "react"
import NavBankSolidIcon from "./NavBankSolidIcon"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  NavBankSolidIcon,
  "https://www.figma.com/design/NpygZcXGZbJqCAWqD2mNEE/MCP?node-id=1-154&t=K21uXhfUQ3HvVvF6-4",
  {
    props: {},
    example: (props) => <NavBankSolidIcon />,
  },
)
