import React from "react"
import NavExchangeSolidIcon from "./NavExchangeSolidIcon"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  NavExchangeSolidIcon,
  "https://www.figma.com/design/NpygZcXGZbJqCAWqD2mNEE/MCP?node-id=1%3A152",
  {
    props: {},
    example: (props) => <NavExchangeSolidIcon />,
  },
)
