// Auto-generated by Style Dictionary
import { Dimensions } from "react-native";

export const radius = {
  none: 0,
  xs: 4,
  sm: 6,
  md: 8,
  lg: 12,
  xl: 16,
  rounded: Dimensions.get("window").height / 2,
} as const;
export type Radii = typeof radius;
export type RadiusValue = Radii[keyof Radii];
export type Radius = keyof Radii;
