// Auto-generated by Style Dictionary
export const spacing = {
  none: 0,
  "50": 2,
  "100": 4,
  "150": 6,
  "200": 8,
  "300": 12,
  "400": 16,
  "500": 20,
  "600": 24,
  "800": 32,
  "1000": 40,
  "1200": 48,
  "1400": 56,
  "1600": 64,
  "2200": 88,
  "2400": 96,
  "3200": 128,
} as const;

export type SpacingValue = (typeof spacing)[keyof typeof spacing];
export type Spacing = keyof typeof spacing;
