// Auto-generated by Style Dictionary
export const groupedTypes = {
  Headings: [
    "header-xl",
    "header-lg",
    "header-md",
    "header-sm",
    "header-xs",
    "header-xxs",
  ],
  Body: [
    "body-lg",
    "body-lg-bold",
    "body-md",
    "body-md-bold",
    "body-sm",
    "body-sm-bold",
    "caption",
    "caption-bold",
  ],
  Button: ["button-lg", "button-sm"],
} as const;

export type FoldTextType =
  (typeof groupedTypes)[keyof typeof groupedTypes][number];

export const typographyStyles: any = {
  "header-xl": { fontFamily: "Geist", fontWeight: "400", fontSize: 40, lineHeight: 44 },
  "header-lg": { fontFamily: "Geist", fontWeight: "400", fontSize: 32, lineHeight: 36 },
  "header-md": { fontFamily: "Geist", fontWeight: "400", fontSize: 24, lineHeight: 28 },
  "header-sm": { fontFamily: "Geist", fontWeight: "400", fontSize: 20, lineHeight: 24 },
  "header-xs": { fontFamily: "Geist", fontWeight: "400", fontSize: 18, lineHeight: 20 },
  "header-xxs": { fontFamily: "Geist", fontWeight: "500", fontSize: 16, lineHeight: 18 },
  "body-lg": { fontFamily: "Geist", fontWeight: "400", fontSize: 16, lineHeight: 24 },
  "body-lg-bold": { fontFamily: "Geist", fontWeight: "500", fontSize: 16, lineHeight: 24 },
  "body-md": { fontFamily: "Geist", fontWeight: "400", fontSize: 14, lineHeight: 20 },
  "body-md-bold": { fontFamily: "Geist", fontWeight: "500", fontSize: 14, lineHeight: 20 },
  "body-sm": { fontFamily: "Geist", fontWeight: "400", fontSize: 12, lineHeight: 16 },
  "body-sm-bold": { fontFamily: "Geist", fontWeight: "500", fontSize: 12, lineHeight: 16 },
  caption: { fontFamily: "Geist", fontWeight: "400", fontSize: 10, lineHeight: 12 },
  "caption-bold": {
    fontFamily: "Geist",
    fontWeight: "600",
    fontSize: 10,
    lineHeight: 12,
  },
  "button-lg": { fontFamily: "Geist", fontWeight: "500", fontSize: 16, lineHeight: 16 },
  "button-sm": { fontFamily: "Geist", fontWeight: "500", fontSize: 14, lineHeight: 14 },
};
